### PR TITLE
add support to laravel 9

### PR DESCRIPTION
**Pull request by blimundo**
Hi. I'am adding support to Laravel 9.

### CODE REVIEW

**Comment by hackeresq** [comment]
Thank you @blimundo , can you update the readme too? Would be nice if it reflects Laravel 9 support.

**Review by blimundo — COMMENTED** [review]
Done :)

**Comment by blimundo** [comment]
We need a new release (version 3.0.6?). When installing the package on Laravel 9 this error occurs:

```λ composer require hackeresq/laravel-settings
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^3.0 for hackeresq/laravel-settings
./composer.json has been updated
Running composer update hackeresq/laravel-settings
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hackeresq/laravel-settings[3.0.0, ..., v3.0.5] require laravel/framework ^6.0|^7.0|^8.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - Root composer.json requires hackeresq/laravel-settings ^3.0 -> satisfiable by hackeresq/laravel-settings[3.0.0, 3.0.3, v3.0.4, v3.0.5].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require hackeresq/laravel-settings:*" to figure out if any version is installable, or "composer require hackeresq/laravel-settings:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
At this point the only way to install on Laravel 9 is through:
```bash
composer require hackeresq/laravel-settings:dev-master
```

**Comment by hackeresq** [comment]
Just issued new release. Can you give that a try?

**Comment by blimundo** [comment]
Its working now. Thanks!

```bash
λ composer require hackeresq/laravel-settings
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^3.0 for hackeresq/laravel-settings
./composer.json has been updated
Running composer update hackeresq/laravel-settings
Loading composer repositories with package information
Updating dependencies
Lock file operations: 5 installs, 0 updates, 0 removals
  - Locking doctrine/cache (2.1.1)
  - Locking doctrine/dbal (2.13.8)
  - Locking doctrine/deprecations (v0.5.3)
  - Locking doctrine/event-manager (1.1.1)
  - Locking hackeresq/laravel-settings (v3.0.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Downloading doctrine/cache (2.1.1)
  - Downloading doctrine/deprecations (v0.5.3)
  - Downloading doctrine/event-manager (1.1.1)
  - Downloading doctrine/dbal (2.13.8)
  - Downloading hackeresq/laravel-settings (v3.0.6)
  - Installing doctrine/cache (2.1.1): Extracting archive
  - Installing doctrine/deprecations (v0.5.3): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
  - Installing doctrine/dbal (2.13.8): Extracting archive
  - Installing hackeresq/laravel-settings (v3.0.6): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
```

**Pull request merged**
